### ISSUE TITLE
grid_2013_2017.csv

### ISSUE THREAD

**Issue by emchristensen** [LCRoysterproject/Data#11]
Data was entered in a weird way -- needs to be converted to long format

**Comment by emchristensen** [comment]
I'm using the columns in Grid_data_Nov_2012_bp.csv as a guide for the LCR_oyster_grid_2013_2017.csv data.  
Questions:
* Date, Trip, and Month columns seem redundant -- we should be able to get away with just Date
* Locality, Site, Bar, Station also seem redundant -- can we get away with just "Station" with the data, and include the other information in a different table (perhaps with lon/lat)?

**Comment by billpine** [comment]
Will reply below
? Date, Trip, and Month columns seem redundant -- we should be able to get away with just Date
answer: Yes, as discussed dates are key to standardize.  Could routinely want to summarize by year or month

?Locality, Site, Bar, Station also seem redundant -- can we get away with just "Station" with the data, and include the other information in a different table (perhaps with lon/lat)?
answer: yes we probably could, but, i chose to do them that way because if, as an example, I want to aggregate by site or bar i can easily do so.  So while it is redundant, it seems like a common way to aggregate (as an example pooling quadrats at one location) and something that if we didn't enter the data that way it might be harder to extract the data from something like "station" and aggregate in other ways.  but I'm open to discussion

?Is "Counter" in the 2012 file the same as "Recorder" in the 2013_2017 file?
answer: yes

?what do "1r" and "1L" mean in the Distance_from column? (this only happens in 4 lines)
answer: i don't know. we used to track whether we went to the "left" or "right" from the "along" but that was sort of abandoned

?the data taken on 11/7/2017 has no values in Distance_from or Distance_along columns
answer: this needs to be discussed with Steve Beck.

?is "Location" from 2013-2017 the same as "Station" in 2012 file?
answer: I think so, need to look at more closely

THANK YOU!!!!!
